version: "3.7"

services:
  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    environment:
      - GRID_TIMEOUT=3600
      - GRID_BROWSER_TIMEOUT=3600

  chrome:
    image: selenium/node-chrome-debug:3.141.59-zirconium
    container_name: chrome
    deploy:
      replicas: 1
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - "./src/main/resources:/dev/shm"
